[web]
web01 ansible_host=192.168.56.101
web02 ansible_host=192.168.56.102

[db]
# Aunque no tengas una base de datos real configurada en este momento, 
# la rúbrica te pide simularla para comprobar la reutilización del rol firewall.
db01 ansible_host=192.168.56.103 

[all:vars]
ansible_user=server